info:
    build:
        version: 0.0.0-dev

spring:
    main:
        show-banner: false
        banner-mode: "off"
    cache:
        ehcache:
          config: classpath:ehcache.xml


nwm:
    base-url: https://api.publicapis.org




